### ISSUE TITLE
Export embauchés : remplacer les Numéros COSELEC en undefined par "rien"

### ISSUE THREAD

**Issue by ketroadec** [anct-cnum/api-admin-conseillers-numerique#576]
> ### Application

Tableau de pilotage

> ### Avec quel type d'utilisateur ?

Admin

> ### Comment y accéder ?

Exports > "Liste des candidates embauchés"

> ### Demande

Dans l'export, il existe la colonne "Nom du comité de sélection". Lorsqu'il n'y a pas de nom, il ne faut pas afficher "undefined" mais laisser le champ vide. Pour ceux qui ont un nom, laisser le nom affiché

**Comment by NerOcrO** [comment]
Bonus : le temps de téléchargement de l'export à été divisé par deux.
